vich_uploader:
    db_driver: orm
    twig: true

    mappings:
        wardrobe_items:
            uri_prefix: /images/wardrobe
            upload_destination: '%kernel.project_dir%/public/images/wardrobe'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true

        outfits:
            uri_prefix: /images/outfits
            upload_destination: '%kernel.project_dir%/public/images/outfits'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            delete_on_update: true
            delete_on_remove: true
