vich_uploader:
    db_driver: orm

    mappings:
        wardrobe_items:
            uri_prefix: /images/wardrobe
            upload_destination: '%kernel.project_dir%/public/images/wardrobe'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true
