# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    timezone: '%env(APP_TIMEZONE)%'
    wardrobe_images_directory: '%kernel.project_dir%/public/images/wardrobe'
    social_post_images_directory: '%kernel.project_dir%/public/uploads/images/social_post'
    outfits_images_directory: '%kernel.project_dir%/public/images/outfits'
    openai_api_key_outfit: '%env(OPENAI_API_KEY_MODEL_4)%'
    openai_model_id: '%env(default:default_openai_model:OPENAI_MODEL_ID)%'
    default_openai_model: 'gpt-4o-mini'
    wardrobeItem_images_directory: '%kernel.project_dir%/public/images/wardrobeItem'
    openai_api_key_wardrobe: '%env(OPENAI_API_KEY_WARDROBE)%'


services:
    # default configuration for services in *this* file
    App\Service\AIAnalyzerService: ~

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\EventSubscriber\VichUploaderSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # App\Controller\AIController:
    #     arguments:
    #         $openaiApiKeyWardrobe: '%openai_api_key_wardrobe%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # IA Services configuration
    App\Service\OutfitRecommendationService:
        arguments:
            $openaiApiKey: '%openai_api_key_outfit%'
            $openaiModelId: '%openai_model_id%'
