services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Service\OutfitRecommendationService:
        arguments:
            $openaiApiKey: 'test_dummy_key'
            $openaiModelId: 'test_model'
